name: JobSuite
main: net.krinsoft.jobsuite.JobCore
version: maven-version-number
author: krinsdeath
load: STARTUP

description: |
  maven-git-descriptor

commands:
  jobsuite:
    aliases: [job, js]
    description: The root command for all of JobSuite's features
    usage: /<command> ...
    
permissions:
  jobsuite.admin.help:
    description: Allows the user to view JobSuite's administrative command help.
    default: op
  jobsuite.admin.cancel:
    description: Allows the user to force the cancellation of a job.
    default: op
  jobsuite.admin.unlock:
    description: Allows the user to force the unlocking of a job.
    default: op